use_frameworks!

platform :ios, '11.0'

target 'FLSwiftyFoundation_Example' do
  pod 'FLSwiftyFoundation', :path => '../'

  target 'FLSwiftyFoundation_Tests' do
    inherit! :search_paths

    
  end
end
